version: "3"

services:
  ghg-fe-prod:
    container_name: ghg-fe-prod
    restart: unless-stopped
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: ghg-fe-env-prod
    ports:
      - "3003:3000"
networks:
  default:
    external:
      name: gateway
